app/models.py
from app import db, login
from flask_login import UserMixin #### THIS IS ONLY FOR THE USER MODEL!!!!
from datetime import datetime as dt, timedelta
from werkzeug.security import generate_password_hash, check_password_hash
import secrets


class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String, unique=True, index=True)
    password = db.Column(db.String)
    created_on = db.Column(db.DateTime, default=dt.utcnow)
    icon = db.Column(db.Integer)
    token = db.Column(db.String, unique=True, index=True)
    token_exp = db.Column(db.DateTime)
    is_admin = db.Column(db.Boolean, default=False)
    # current_user.followed.all() #all the people current user is following
    # current_user.followers.all() # all the people following the current user

    ##################################################
    ############## Methods for Token auth ############
    ##################################################    
    def get_token(self, exp=86400):
        current_time = dt.utcnow()
        # If their is a token and it is valid we willtreturn the token
        if self.token and self.token_exp > current_time+timedelta(seconds=60):
            return self.token
        # There was no token or It was expired, so make a new token
        self.token = secrets.token_urlsafe(32)
        self.token_exp = current_time + timedelta(seconds=exp)
        self.save()
        return self.token

    def revoke_token(self):
        self.token_exp = dt.utcnow() - timedelta(seconds=60)
    
    @staticmethod
    def check_token(token):
        # u=User.query.filter(User.token == token).first()
        u = User.query.filter_by(token = token).first()
        if not u or u.token_exp < dt.utcnow():
            return None
        return u



    #########################################
    ############# End Methods for tokens ####
    #########################################

    # Should return a unique identifing string
    def __repr__(self):
        return f'<User: {self.email} | {self.id} >'

    # Human Readable repr
    def __str__(self):
        return f'<User: {self.email} | {self.first_name} {self.last_name}>'
    
    # salt and hash our password to make it hard to steal
    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    def check_hashed_password(self, login_password):
        return check_password_hash(self.password, login_password)

    # save the user to the db
    def save(self):
        db.session.add(self) # add the user to out session
        db.session.commit() # saves the session to the database

    def to_dict(self):
        return {
            'id':self.id,
            'first_name':self.first_name,
            'last_name':self.last_name,
            'email':self.email,
            'created_on' :self.created_on,
            'icon':self.icon,
            'token':self.token,
            'is_admin':self.is_admin
        }

    def from_dict(self, data):
        self.first_name = data['first_name']
        self.last_name = data['last_name']
        self.email= data['email']
        self.password = self.hash_password(data['password'])
        self.icon = data['icon']

    def get_icon_url(self):
        return f"https://avatars.dicebear.com/api/adventurer/{self.icon}.svg"

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class Post(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    created_on = db.Column(db.DateTime, default=dt.utcnow)
    date_modified = db.Column(db.DateTime, onupdate=dt.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<Post: {self.id} | {self.body[:15]}>'

    def edit(self, new_body):
        self.body=new_body

    def to_dict(self):
        return{
            'id':self.id,
            'body':self.body,
            'created_on':self.created_on,
            'date_modified':self.date_modified,
            'user_id':self.user_id,
        }

    # save the post to the db
    def save(self):
        db.session.add(self) # add the post to out session
        db.session.commit() # saves the session to the database
    
    def delete(self):
        db.session.delete(self)
        db.session.commit()

app/__init__.py
from flask import Flask, render_template
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment
from flask_cors import CORS
import os

db = SQLAlchemy()
migrate = Migrate(compare_type=True)
login = LoginManager()
moment = Moment()

if os.environ.get('FLASK_DEBUG'):
    cors = CORS()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    moment.init_app(app)

    login.login_view = 'pokemon.login'
    login.login_message = 'You need to login.'
    login.login_message_category = 'danger'

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from .blueprints.pokemon import bp as pokemon_bp
    app.register_blueprint(pokemon_bp)

    @app.route('/', methods=['GET', 'POST'])
    def index():
        return render_template('index.html.j2')


    return app

from app import models

app/blueprints/pokemon/__init__.py
from flask import Blueprint

bp = Blueprint('pokemon', __name__, url_prefix='/pokemon')

from . import routes

app/blueprints/pokemon/routes.py
from . import bp as pokemon
from flask import render_template, request, flash, redirect, url_for
import requests

@pokemon.route('/search', methods=['GET', 'POST'])
def search():
    if request.method =='POST':
        poke = request.form.get("search")
        url = f'https://pokeapi.co/api/v2/pokemon/{poke}'
        response = requests.get(url)
        if not response.ok:
            error_string = "We had an Unexpected Error"
            return render_template('pokemon.html.j2', error = error_string)
        if not response.json():
            error_string = "That's Not A Pokmeon. Please Try Again"
            return render_template('pokemon.html.j2', error = error_string)
        data = response.json()
        poke_dict={
            "name":data['name'],
            "ability":data['abilities'][0]['ability']['name'],
            "defense":data['stats'][2]['base_stat'],
            "attack":data['stats'][1]['base_stat'],
            "HP":data['stats'][0]['base_stat'],
            "sprite":data['sprites']['front_shiny']
        }
        return render_template('pokemon.html.j2', poke=poke_dict)

    return render_template('pokemon.html.j2')

@pokemon.route('/my_pokemon')
def my_pokemon():
    return render_template('my_pokemon.html.j2')

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>P.B.S. - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

    <link rel="shortcut icon" href="{{url_for('static', filename='images/favicon.ico')}}" type="image/x-icon">

    {% block css %}
    {% endblock %}
    {{ moment.include_moment() }}
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
{% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for class, message in messages %}
            <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

    {% include './includes/nav.html.j2' %}
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('index')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">Battle</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">Your Pokemon</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('pokemon.search')}}">Search Pokemon</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/index.html.j2
{% extends './base.html.j2' %}

app/templates/login.html.j2
{% extends './base.html.j2' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="col-6 offset-3">
        <h1>Login</h1>
        <form action="{{url_for('auth.login')}}" method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control") }}

                {% for error in form.email.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
                {% for error in form.password.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div>
                {{ form.submit(class="btn btn-primary") }}
                <div>
                    <small style="color:red;">{{ loginerror }}</small>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/my_pokemon.html.j2
{% extends './base.html.j2' %}

{% block content %}

{% endblock %}

app/templates/pokemon.html.j2
{% extends './base.html.j2' %}

{% block content %}
    <form action = "{{url_for('pokemon.search')}}" method="POST">
        <input type="search" class="form-control col-auto"
        placeholder="Search a Pokemon"
        name="search" />
        <input class="btn btn-primary col-auto" type="submit" value="Search">
    </form>
{% if poke %}
    <table class="table table-striped table-hover table-dark mt-5">
        <thead>
            <tr>
                <th scope="col">Pokemon</th>
                <th scope="col">Name</th>
                <th scope="col">ability</th>
                <th scope="col">defense</th>
                <th scope="col">attack</th>
                <th scope="col">HP</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><img src="{{ poke.sprite }}" alt="Pokemone Image"></td>
                <td>{{ poke.name }}</td>
                <td>{{ poke.ability }}</td>
                <td>{{ poke.defense }}</td>
                <td>{{ poke.attack }}</td>
                <td>{{ poke.HP }}</td>
            </tr>
        </tbody>
    </table>
    <form action = "{{url_for('pokemon.search')}}" method="GET">
        <input class="btn btn-primary col-auto" type="submit" value="Catch" name="catch">
    </form>
{% endif %}
{% endblock %}

app/templates/register.html.j2
{% extends './base.html.j2' %}

{% block title %}
    {% if current_user.is_authenticated %}
        Edit Profile
    {% else %}
        Register
    {% endif %}
{% endblock %}

{% block content %}
    <div class="col-6 offset-3">
        <h1>
            {% if current_user.is_authenticated %}
                Edit Profile
            {% else %}
                Register
            {% endif %}
        </h1>
        <form action="{{ url_for('auth.edit_profile') if current_user.is_authenticated else  url_for('auth.register')  }}" method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.icon.label(class="form-label") }}
                <div>
                    {% for subfield in form.icon %}
                        {{subfield}}
                        {{subfield.label | safe}}
                    {% endfor %}
                </div>
            </div>

            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control", value = current_user.email) }}

                {% for error in form.email.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.first_name.label(class="form-label") }}
                {{ form.first_name(class="form-control", value = current_user.first_name) }}

                {% for error in form.first_name.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.last_name.label(class="form-label") }}
                {{ form.last_name(class="form-control", value = current_user.last_name) }}

                {% for error in form.last_name.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(class="form-control") }}
                {% for error in form.password.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.confirm_password.label(class="form-label") }}
                {{ form.confirm_password(class="form-control") }}

                {% for error in form.confirm_password.errors %}
                    <small style="color:red;">{{ error }}</small>
                {% endfor %}
            </div>
            <div>
                {{ form.submit(class="btn btn-primary") }}

            </div>
        </form>
    </div>
{% endblock %}